name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'


permissions:
  contents: write

jobs:
  build:
    name: Build for GNU/Linux
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64, 386]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24' # o la versión que uses

      - name: Build binary
        run: |
          mkdir -p build
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} \
          go build -o build/http_client_tui-${{ matrix.goos }}-${{ matrix.goarch }} 

      - name: Upload release artifacts
        uses: softprops/action-gh-release@v2
        with:
          files: build/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

